[build]
dir = "Guess_the_Number"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python app.py"

[variables]
PORT = "8000"
